[WIP]Mypage
tsuyoshit201603/freemarket_sample_57d pull request #18
Opened 2019-08-29 13:22 UTC by hashryo

2019-08-30 04:37 UTC, JUN1113-program commented on app/assets/stylesheets/identifications/_index.scss
> +    border-bottom: 1px solid #f5f5f5;
$backColor: #f4f4f4;を使っていただけるとありがたいです

2019-08-30 04:40 UTC, JUN1113-program commented on app/views/identifications/index.html.haml
> +          %input{ :class => "identification__body__form__data", :placeholder => "例）1234567"}
ハッシュロケットをシンボル系に変更をお願いします

2019-08-30 04:41 UTC, opazein reviewed
LGTMです

2019-08-30 04:42 UTC, hashryo reviewed
lgtm

2019-08-30 04:42 UTC, HiromiHiguchi commented
ありがとうございます！
LGTMです！

2019-08-30 04:43 UTC, tsuyoshit201603 commented on app/assets/stylesheets/identifications/_index.scss
> +    border-bottom: 1px solid #f5f5f5;
修正しました！

2019-08-30 04:44 UTC, tsuyoshit201603 commented on app/views/identifications/index.html.haml
> +          %input{ :class => "identification__body__form__data", :placeholder => "例）1234567"}
修正しました！

2019-08-30 04:44 UTC, tsuyoshit201603 reviewed
lgtm

2019-08-31 02:02 UTC, yuki-uchida requested changes

2019-08-31 02:02 UTC, yuki-uchida commented on app/views/identifications/index.html.haml
> +            %option
activehashで管理しましょう

2019-08-31 04:46 UTC, tsuyoshit201603 commented on app/views/identifications/index.html.haml
> +            %option
修正しました！

2019-08-31 04:48 UTC, yuki-uchida commented
LGTMです

2019-08-31 05:01 UTC, merged